# Generated by Django 2.2.4 on 2019-11-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191125_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
