# Generated by Django 2.2.4 on 2019-11-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191125_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_img',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images'),
        ),
    ]
