# Generated by Django 2.0 on 2019-12-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_auto_20191130_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('min_BMR', models.IntegerField()),
                ('max_BMR', models.IntegerField()),
                ('plan_features', models.TextField()),
                ('discount_on_products', models.IntegerField()),
            ],
        ),
    ]
