# Generated by Django 2.2.4 on 2019-12-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
