# Generated by Django 2.2.4 on 2019-12-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_subscriptionplan_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userextension',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userextension',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
