# Generated by Django 2.2.4 on 2019-12-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_auto_20191224_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='max_BMR',
            new_name='max_BMR_male',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='min_BMR',
            new_name='min_BMR_male',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_BMR_female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='min_BMR_female',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
