# Generated by Django 2.2.4 on 2019-12-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_auto_20191227_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmrvalues',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
