# Generated by Django 2.2.4 on 2020-02-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerBio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=200)),
                ('trainer_bio', models.TextField()),
                ('trainer_gallery', models.TextField()),
                ('trainer_facebook_link', models.URLField(blank=True, null=True)),
                ('trainer_instagram_link', models.URLField(blank=True, null=True)),
                ('trainer_linkedin_link', models.URLField(blank=True, null=True)),
                ('trainer_contact', models.BigIntegerField()),
                ('trainer_address', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
