# Generated by Django 2.2.4 on 2020-02-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerbio',
            name='trainer_gallery',
            field=models.TextField(blank=True, null=True),
        ),
    ]
