# Generated by Django 2.2.4 on 2020-01-31 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='session_key',
            field=models.ForeignKey(blank=True, db_column='OrderSession', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.OrderSession', to_field='session_key'),
        ),
    ]
